name: Build

on: 
  - push

jobs:
  dummy-chain:
    name: Build chain
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod download

      - name: Build project
        run: make build
