name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod download

      - name: Build binaries
        run: make release

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "dist/*"
          allowUpdates: true
